server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Send API requests to the Django backend container
    location /api/ {
        # Bắt buộc phải có dòng này: Sử dụng DNS nội bộ của Docker
        resolver 127.0.0.11 valid=30s;
        
        # Đưa URL vào biến để ép Nginx resolve IP khi có request thực tế, không resolve lúc startup
        set $upstream_backend http://backend:8000;
        proxy_pass $upstream_backend;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Vue SPA routes
    location / {
        try_files $uri $uri/ /index.html;
    }
}
